### ISSUE TITLE
Support Scala Native 

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#458]
This is a meta issue to follow what's left to do to support fully Scala Native.

 - [x] Extract the platform in sbt-bloop (Done in #457)
 - [ ] Extract all the configuration options relevant to Scala Native & store them in the config
 - [x] Compile Scala Native projects (Done in #457)
 - [x] Link Scala Native projects (Done in #457)
    - [ ] Autocomplete `native-link` only for Scala Native projects
 - [x] Run Scala Native projects (Done in #457)
 - [ ] Test Scala Native projects (blocked on scala-native/scala-native#1234)

**Comment by jvican** [comment]
Fixed in #457.
